// docs/dxp/7.x/en/developing-applications/developing-a-single-page-application/using-vue/liferay-c7z3.zip/c7z3-impl/src/components/ViewGuestbook.vue
<template>
  <div class="ml-2 mr-2">
    <h1>ACME Guestbook</h1>
    <table class="table table-striped table-bordered mb-4">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Message</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="entry in entries" :key="entry.id">
          <td>{{entry.name}}</td>
          <td>{{entry.message}}</td>
        </tr>
      </tbody>
    </table>
    <div class="button-footer">
      <routerLink to="/add-entry" class="btn btn-outline-secondary">Add Entry</routerLink>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ViewGuestbook',
  props: ['entries']
}
</script>

// docs/dxp/7.x/en/developing-applications/developing-a-single-page-application/using-react/liferay-r3z7.zip/before/acme-react-guestbook-app-before/src/view-guestbook.js
import React from 'react';
import { Link } from 'react-router-dom';

class Guestbook extends React.Component {

  render() {
    
    return (
      <div className="guestbook">
        <h1>ACME Guestbook</h1>
        <table className="table table-striped table-bordered mb-4">
          <thead className="thead-light">
            <tr>
              <th>Name</th>
              <th>Message</th>
            </tr>
          </thead>
          <CreateTableData entryData={this.props.entries}/>
        </table>
        <div>
          <Link to="/add-entry" onClick={this.props.resetRedirect} className="btn btn-outline-secondary">Add Entry</Link>
        </div>
      </div>
    );
  }
}
const CreateTableData = props => {

    const entries = props.entryData.map((row, index) => {
          
      return (
        <tr key={index}>
          <td>{row.name}</td>
          <td>{row.message}</td>
        </tr>
      )
    });
    
    return <tbody>{entries}</tbody>;

}


export default Guestbook;
